"""Code generated by tools/genrouter.py. DO NOT EDIT.

Checked in, this is the default: a health check route and nothing
else, so this repo builds and deploys standalone with no external
route-providing dependency until something overrides it (see
.github/actions/router, or run `python tools/genrouter.py
--router-module=...` directly).
"""


def register(app):
    """Registers this deployment's routes onto app."""

    @app.route("/healthz")
    def healthz():
        return "ok", 200
