"""Command genrouter regenerates routersource/source.py and the
router-package line in requirements.txt - the two places main.py's
dependency on an external route-providing repo ever shows up. Run it
with --router-module (and --router-package, the pip requirement spec
that provides it) to point this shell at a specific route-providing
package, or with no flags to reset both back to the default health
check.
"""
import argparse
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

SOURCE_DEFAULT = '''"""Code generated by tools/genrouter.py. DO NOT EDIT.

Checked in, this is the default: a health check route and nothing
else, so this repo builds and deploys standalone with no external
route-providing dependency until something overrides it (see
.github/actions/router, or run `python tools/genrouter.py
--router-module=...` directly).
"""


def register(app):
    """Registers this deployment's routes onto app."""

    @app.route("/healthz")
    def healthz():
        return "ok", 200
'''

SOURCE_REMOTE = '''"""Code generated by tools/genrouter.py. DO NOT EDIT."""

from {router_module} import register

__all__ = ["register"]
'''

REQUIREMENTS_MARKER = "# --- router-package (managed by tools/genrouter.py) ---"


def render_source(router_module: str) -> str:
    if router_module:
        return SOURCE_REMOTE.format(router_module=router_module)
    return SOURCE_DEFAULT


def render_requirements(requirements_path: pathlib.Path, router_package: str) -> str:
    text = requirements_path.read_text()
    marker_index = text.index(REQUIREMENTS_MARKER)
    base = text[: marker_index + len(REQUIREMENTS_MARKER)]
    if router_package:
        return base + "\n" + router_package + "\n"
    return base + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--router-module",
        default="",
        help="dotted import path of a module exposing register(app); empty resets to the default health check",
    )
    parser.add_argument(
        "--router-package",
        default="",
        help=(
            "pip requirement spec that provides --router-module, e.g. "
            "'git+https://github.com/dash-xd/gcp-python-function-inspector.git@main'; "
            "empty removes any router package from requirements.txt"
        ),
    )
    parser.add_argument("--source-out", default=str(ROOT / "routersource" / "source.py"))
    parser.add_argument("--requirements", default=str(ROOT / "requirements.txt"))
    args = parser.parse_args()

    pathlib.Path(args.source_out).write_text(render_source(args.router_module))

    requirements_path = pathlib.Path(args.requirements)
    requirements_path.write_text(render_requirements(requirements_path, args.router_package))


if __name__ == "__main__":
    main()
